version: '3.7'
services: 
    some-node-api:
        build: 
            context: .
            dockerfile: Dockerfile_1
        volumes: 
            - .:/app
        expose:
            - "5000"
        ports:
            - "5000:5000"
        links:
            - postgres:postgres
        env_file:
            - .env
        command: "pm2-runtime ecosystem.config.js"
    postgres:
        image: postgres
        ports:
            - "5432:5432"
        env_file:
            - database.env
        volumes:
            - node-app-db-data:/var/lib/postgresql/data
    nginx:
        restart: always
        build: 
            context: ./nginx
            dockerfile: Dockerfile_2
        ports:
            - "80:80"
        links:
            - some-node-api:some-node-api
volumes:
    node-app-db-data:
